printWidth: 80
tabWidth: 2
useTabs: false
semi: true
singleQuote: false
trailingComma: all
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: avoid
plugins:
  - prettier-plugin-svelte
overrides:
  - files: "*.svelte"
    options:
      parser: "svelte"
